global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service-dev:3001']

  - job_name: 'product-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['product-service-dev:3000']

  - job_name: 'order-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['order-service-dev:3002']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend-app-dev:80']
